/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheArchitectRouteImport } from './routes/the-architect'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PersonalDevelopmentFrameworkRouteImport } from './routes/personal-development-framework'
import { Route as OrganizationalDevelopmentRouteImport } from './routes/organizational-development'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MediaRouteImport } from './routes/media'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExecutiveCoachingRouteImport } from './routes/executive-coaching'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ClarityosRouteImport } from './routes/clarityos'
import { Route as BookASessionRouteImport } from './routes/book-a-session'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as FrameworksSlugRouteImport } from './routes/frameworks.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TheArchitectRoute = TheArchitectRouteImport.update({
  id: '/the-architect',
  path: '/the-architect',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDevelopmentFrameworkRoute =
  PersonalDevelopmentFrameworkRouteImport.update({
    id: '/personal-development-framework',
    path: '/personal-development-framework',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationalDevelopmentRoute =
  OrganizationalDevelopmentRouteImport.update({
    id: '/organizational-development',
    path: '/organizational-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveCoachingRoute = ExecutiveCoachingRouteImport.update({
  id: '/executive-coaching',
  path: '/executive-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarityosRoute = ClarityosRouteImport.update({
  id: '/clarityos',
  path: '/clarityos',
  getParentRoute: () => rootRouteImport,
} as any)
const BookASessionRoute = BookASessionRouteImport.update({
  id: '/book-a-session',
  path: '/book-a-session',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksSlugRoute = FrameworksSlugRouteImport.update({
  id: '/frameworks/$slug',
  path: '/frameworks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BookRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/book-a-session': typeof BookASessionRoute
  '/clarityos': typeof ClarityosRoute
  '/connect': typeof ConnectRoute
  '/executive-coaching': typeof ExecutiveCoachingRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/organizational-development': typeof OrganizationalDevelopmentRoute
  '/personal-development-framework': typeof PersonalDevelopmentFrameworkRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-architect': typeof TheArchitectRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/book/$slug': typeof BookSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/book-a-session': typeof BookASessionRoute
  '/clarityos': typeof ClarityosRoute
  '/connect': typeof ConnectRoute
  '/executive-coaching': typeof ExecutiveCoachingRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/organizational-development': typeof OrganizationalDevelopmentRoute
  '/personal-development-framework': typeof PersonalDevelopmentFrameworkRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-architect': typeof TheArchitectRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/book/$slug': typeof BookSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/frameworks': typeof FrameworksIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/book-a-session': typeof BookASessionRoute
  '/clarityos': typeof ClarityosRoute
  '/connect': typeof ConnectRoute
  '/executive-coaching': typeof ExecutiveCoachingRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/organizational-development': typeof OrganizationalDevelopmentRoute
  '/personal-development-framework': typeof PersonalDevelopmentFrameworkRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-architect': typeof TheArchitectRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/book/$slug': typeof BookSlugRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/book-a-session'
    | '/clarityos'
    | '/connect'
    | '/executive-coaching'
    | '/mcp'
    | '/media'
    | '/newsletter'
    | '/organizational-development'
    | '/personal-development-framework'
    | '/services'
    | '/sitemap.xml'
    | '/the-architect'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/book/$slug'
    | '/frameworks/$slug'
    | '/insights/$slug'
    | '/frameworks/'
    | '/insights/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/book-a-session'
    | '/clarityos'
    | '/connect'
    | '/executive-coaching'
    | '/mcp'
    | '/media'
    | '/newsletter'
    | '/organizational-development'
    | '/personal-development-framework'
    | '/services'
    | '/sitemap.xml'
    | '/the-architect'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/book/$slug'
    | '/frameworks/$slug'
    | '/insights/$slug'
    | '/frameworks'
    | '/insights'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/book-a-session'
    | '/clarityos'
    | '/connect'
    | '/executive-coaching'
    | '/mcp'
    | '/media'
    | '/newsletter'
    | '/organizational-development'
    | '/personal-development-framework'
    | '/services'
    | '/sitemap.xml'
    | '/the-architect'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/book/$slug'
    | '/frameworks/$slug'
    | '/insights/$slug'
    | '/frameworks/'
    | '/insights/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  BookASessionRoute: typeof BookASessionRoute
  ClarityosRoute: typeof ClarityosRoute
  ConnectRoute: typeof ConnectRoute
  ExecutiveCoachingRoute: typeof ExecutiveCoachingRoute
  McpRoute: typeof McpRoute
  MediaRoute: typeof MediaRoute
  NewsletterRoute: typeof NewsletterRoute
  OrganizationalDevelopmentRoute: typeof OrganizationalDevelopmentRoute
  PersonalDevelopmentFrameworkRoute: typeof PersonalDevelopmentFrameworkRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TheArchitectRoute: typeof TheArchitectRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  FrameworksSlugRoute: typeof FrameworksSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-architect': {
      id: '/the-architect'
      path: '/the-architect'
      fullPath: '/the-architect'
      preLoaderRoute: typeof TheArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-development-framework': {
      id: '/personal-development-framework'
      path: '/personal-development-framework'
      fullPath: '/personal-development-framework'
      preLoaderRoute: typeof PersonalDevelopmentFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizational-development': {
      id: '/organizational-development'
      path: '/organizational-development'
      fullPath: '/organizational-development'
      preLoaderRoute: typeof OrganizationalDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-coaching': {
      id: '/executive-coaching'
      path: '/executive-coaching'
      fullPath: '/executive-coaching'
      preLoaderRoute: typeof ExecutiveCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarityos': {
      id: '/clarityos'
      path: '/clarityos'
      fullPath: '/clarityos'
      preLoaderRoute: typeof ClarityosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-session': {
      id: '/book-a-session'
      path: '/book-a-session'
      fullPath: '/book-a-session'
      preLoaderRoute: typeof BookASessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/$slug': {
      id: '/frameworks/$slug'
      path: '/frameworks/$slug'
      fullPath: '/frameworks/$slug'
      preLoaderRoute: typeof FrameworksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof BookRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookSlugRoute: typeof BookSlugRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSlugRoute: BookSlugRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  BookASessionRoute: BookASessionRoute,
  ClarityosRoute: ClarityosRoute,
  ConnectRoute: ConnectRoute,
  ExecutiveCoachingRoute: ExecutiveCoachingRoute,
  McpRoute: McpRoute,
  MediaRoute: MediaRoute,
  NewsletterRoute: NewsletterRoute,
  OrganizationalDevelopmentRoute: OrganizationalDevelopmentRoute,
  PersonalDevelopmentFrameworkRoute: PersonalDevelopmentFrameworkRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TheArchitectRoute: TheArchitectRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  FrameworksSlugRoute: FrameworksSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
